### ISSUE TITLE
Can't install from Auto1111

### ISSUE THREAD

**Issue by realenuf** [Zetaphor/sd-library-notes#4]
When I paste  https://github.com/Zetaphor/sd-library-notes and select "install" on automatic1111 SD, I get an error message:
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v https://github.com/Zetaphor/sd-library-notes /media/iwoolf/BigDrive/stable-diffusion-webui/tmp/sd-library-notes stderr: 'Cloning into '/media/iwoolf/BigDrive/stable-diffusion-webui/tmp/sd-library-notes'... fatal: protocol ' https' is not supported '

I'm on Ubuntu 22.04.2, using the Chrome browser. I also tried just http, and got the same error 'http' is not supported. I haven't tried installing other extensions this way, but it looks like a SD issue that fails with any extension installed by URL.

Here are the lines from the CLI:
Error completing request
Arguments: ('', ' https://github.com/Zetaphor/sd-library-notes') {}
Traceback (most recent call last):
  File "/media/iwoolf/BigDrive/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/media/iwoolf/BigDrive/stable-diffusion-webui/modules/ui_extensions.py", line 145, in install_extension_from_url
    repo = git.Repo.clone_from(url, tmpdir)
  File "/media/iwoolf/BigDrive/stable-diffusion-webui/venv/lib/python3.9/site-packages/git/repo/base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/media/iwoolf/BigDrive/stable-diffusion-webui/venv/lib/python3.9/site-packages/git/repo/base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "/media/iwoolf/BigDrive/stable-diffusion-webui/venv/lib/python3.9/site-packages/git/util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "/media/iwoolf/BigDrive/stable-diffusion-webui/venv/lib/python3.9/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v  https://github.com/Zetaphor/sd-library-notes /media/iwoolf/BigDrive/stable-diffusion-webui/tmp/sd-library-notes
  stderr: 'Cloning into '/media/iwoolf/BigDrive/stable-diffusion-webui/tmp/sd-library-notes'...
fatal: protocol ' https' is not supported

**Comment by Zetaphor** [comment]
I've had that error occur before with SD, try restarting and try again and see if you're still having issues

**Comment by Zetaphor** [comment]
Worst case scenario you can always manually download the repo and paste the folder into your extensions folder, but then you won't be able to get updates

**Comment by Zetaphor** [comment]
You could also try adding the `--enable-insecure-extension-access` flag to your webui-user.sh command line arguments

**Comment by arcum42** [comment]
Try pasting in https://github.com/Zetaphor/sd-library-notes.git instead...

**Comment by realenuf** [comment]
I tried all your suggestions, but they didn't work, so I manually git cloned the repo into the extensions folder. I restarted SD, and it shows up under installed extensions. Now I'll add some text files with trigger words. Where do they show up in the UI?

**Comment by Zetaphor** [comment]
Check the screenshot in the README, they're on the left hand side with your other options. I'm going to work on improving the readme and in-UI help
