### ISSUE TITLE
Add a tab for general notes not related to a model

### ISSUE THREAD

**Issue by arcum42** [Zetaphor/sd-library-notes#5]
Basically, have it scan a notes folder and list all the md/txt files in that folder in a separate tab so that you have someplace for more general notes, things like prompt templates for things you often use in your prompts, boilerplate negative prompts, etc. You could potentially also put the readme in there, and roll the About tab into it.

You could also potentially add a setting where you can tell it where the folder is located into the settings tab at some point as well.

**Comment by Zetaphor** [comment]
Good idea, it's now implemented with [d5165a5](https://github.com/Zetaphor/sd-library-notes/commit/d5165a5ca76ad74a6feb3de8a07cf076936cf951). Any text or markdown files in the `notes` folder under your SD root will be recognized by that tab

I definitely need to implement a settings tab for that and more settings.

**Comment by arcum42** [comment]
@Zetaphor 
Looks good!

Settings would definitely be nice, and I feel like the readme in the About tab should probably mention that general notes go in the notes folder in the meantime.
